[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "eyeball"
version="0.1.0"
description = "Text detector with DBNet"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "Apache-2.0"}
dependencies = [
    "pyyaml",
    "numpy",
    "opencv-python",
    "Pillow",
    "torch",
    "torchvision", 
    "lenses",
	"icecream",
]


[[authors]] 
author = "Hung Nguyen"
email = "ndgnuh@protonmail.com"

[tool.setuptools]
packages = ["eyeball"]

