weights: https://github.com/ndgnuh/eyeball/releases/download/weights/db_shufflenet_v2-best.pt

backbone: fpn_shufflenet_v2_x0_5
backbone_options:
  output_size: 256

head: DBHead
head_options:
  input_size: 256
  activation: ReLU

processor: DBProcessor
processor_options: {}

loss: LossMixin
loss_options:
  mode: db

image_width: 768
image_height: 512

