weights: https://github.com/ndgnuh/eyeball/releases/download/weights/db_mobilenet_v3_small-best.pt

backbone: fpn_mobilenet_v3_small
backbone_options:
  output_size: 256

head: DBHead
head_options:
  input_size: 256
  activation: ReLU

processor: DBProcessor
processor_options: {}

loss: DBLoss
loss_options: {}

image_width: 1024
image_height: 1024

