backbone: fpn_mobilenet_v3_large
backbone_options:
  output_size: 256

head: DBHead
head_options:
  input_size: 256
  activation: Hardshrink

processor: DBProcessor
processor_options: {}

loss: DBLoss
loss_options: {}

image_width: 1024
image_height: 1024
