# Rejects wizardry
# Returns to KISS redundancy
weights: storage/weights/db_resnet18-latest.pt

backbone: fpn_resnet18
backbone_options:
  output_size: 256

head: DBHead
head_options:
  input_size: 256
  activation: ReLU

processor: DBProcessor
processor_options: {}

loss: DBLoss
loss_options: {}

image_width: 1024
image_height: 1024

