weights: https://github.com/ndgnuh/eyeball/releases/download/weights/db_resnet34-best.pt

backbone: fpn_resnet34
backbone_options:
  output_size: 256

head: DBHead
head_options:
  input_size: 256
  activation: ReLU

processor: DBProcessor
processor_options: {}

loss: DBLoss
loss_options: {}

image_width: 1024
image_height: 1024

