optimizer: AdamW
optimizer_options:
  lr: 0.000099

lr_scheduler: CosineAnnealingLR
lr_scheduler_options:
  T_max: 50000

total_steps: 50000
print_every: 500
validate_every: 2500

train_data: toybox/word-level-megane/
validate_data: toybox/word-level-megane/
test_data: toybox/word-level-megane/
dataloader_options:
  batch_size: 1


lightning_options:
  accelerator: gpu
