lr: 0.0001
optimizer: AdamW
optimizer_options: {}

lr_scheduler: OneCycleLR
lr_scheduler_options:
  max_lr: 0.0003
  total_steps: 10000

total_steps: 10_000
validate_every: 500
print_every: 500

train_data: funsd/train/
validate_data: funsd/test/
test_data: funsd/test/
dataloader_options:
  batch_size: 4
  num_workers: 6


lightning_options:
  accelerator: gpu
