optimizer: AdamW
optimizer_options:
  lr: 0.0007

lr_scheduler: CosineAnnealingLR
lr_scheduler_options:
  T_max: 10_000

total_steps: 10_000
print_every: 100
validate_every: 500

train_data: funsd/train/
validate_data: funsd/test/
test_data: funsd/test/
dataloader_options:
  batch_size: 2
  num_workers: 6


lightning_options:
  accelerator: gpu
